// src/.../MappedPoliciesTargetTablesPage.tsx
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Box, CircularProgress } from '@mui/material';

import PolicyScannerTable, {
  type ActionButton,
  type ColumnConfig,
} from '../PolicyScannerTable/PolicyScannerTable';

import { MappedPoliciesAPI } from '../../../../api/endpoints/policyScanner.api';
import type { PolicyItem } from '../../../../types/policyScanner.types';
import styles from '../../PolicyScanner.module.scss';

interface MappedPoliciesTargetTablesPageProps {
  complianceId: string;
  complianceName: string;
  onLoadingChange?: (loading: boolean) => void;
}

const MappedPoliciesTargetTablesPage: React.FC<MappedPoliciesTargetTablesPageProps> = ({
  complianceId,
  complianceName,
  onLoadingChange,
}) => {
  const [policies, setPolicies] = useState<PolicyItem[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isSaving, setIsSaving] = useState<boolean>(false);
  const [isApproving, setIsApproving] = useState<boolean>(false);

  const hasSelectedRows = useMemo(() => policies.some((p) => p.selected), [policies]);

  // Notify parent of loading state changes
  useEffect(() => {
    onLoadingChange?.(isLoading || isSaving || isApproving);
  }, [isLoading, isSaving, isApproving, onLoadingChange]);

  useEffect(() => {
    const fetchPolicies = async () => {
      if (!complianceId) return;

      setIsLoading(true);
      try {
        const response = await MappedPoliciesAPI.getPolicies(complianceId);

        if (response.success) {
          setPolicies(response.policies);
        } else {
          console.error('Failed to fetch mapped policies:', response.message);
        }
      } catch (error) {
        console.error('Error fetching mapped policies:', error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchPolicies();
  }, [complianceId]);

  const handleCheckboxChange = useCallback((id: number | string) => {
    setPolicies((prev) =>
      prev.map((policy) =>
        policy.id === id ? { ...policy, selected: !policy.selected } : policy
      )
    );
  }, []);

  const handleSelectAll = useCallback((selectAll: boolean) => {
    setPolicies((prev) => prev.map((policy) => ({ ...policy, selected: selectAll })));
  }, []);

  const clearSelections = useCallback(() => {
    setPolicies((prev) => prev.map((policy) => ({ ...policy, selected: false })));
  }, []);

  const handleCommentChange = useCallback((id: number | string, field: string, value: string) => {
    if (field === 'commentsOnDeltaLoad') {
      setPolicies((prev) =>
        prev.map((policy) =>
          policy.id === id ? { ...policy, commentsOnDeltaLoad: value } : policy
        )
      );
    }
  }, []);

  const handleSave = useCallback(async () => {
    setIsSaving(true);
    try {
      const response = await MappedPoliciesAPI.savePolicies({ policies, complianceId });

      if (response.success) console.log(response.message);
      else console.error('Failed to save policies:', response.message);
    } catch (error) {
      console.error('Error saving policies:', error);
    } finally {
      setIsSaving(false);
    }
  }, [policies, complianceId]);

  const handleApprove = useCallback(async () => {
    const selectedPolicyIds = policies.filter((p) => p.selected).map((p) => p.id);

    if (selectedPolicyIds.length === 0) {
      console.log('No policies selected');
      return;
    }

    setIsApproving(true);
    try {
      const response = await MappedPoliciesAPI.approvePolicies({
        policyIds: selectedPolicyIds,
        complianceId,
      });

      if (response.success) {
        setPolicies((prev) =>
          prev.map((policy) =>
            selectedPolicyIds.includes(policy.id)
              ? { ...policy, approvalStatus: 'APPROVED' }
              : policy
          )
        );
        clearSelections();
        console.log(response.message);
      } else {
        console.error('Failed to approve policies:', response.message);
      }
    } catch (error) {
      console.error('Error approving policies:', error);
    } finally {
      setIsApproving(false);
    }
  }, [policies, complianceId, clearSelections]);

  const columns: ColumnConfig[] = [
    { key: 'policyId', header: 'Policy ID', type: 'text', className: styles.policyIdColumn },
    { key: 'policyDescription', header: 'Policy description', type: 'text', className: styles.descriptionColumn },
    {
      key: 'autoGeneratedTable',
      header: 'Auto generated target table',
      type: 'text',
      className: styles.autoGeneratedColumn,
    },
    {
      key: 'targetTableColumns',
      header: 'Target table columns',
      type: 'text',
      className: styles.targetTableColumnsColumn,
    },
    {
      key: 'commentsOnDeltaLoad',
      header: 'Comments on delta load check',
      type: 'comment',
      className: styles.commentsColumn,
      editable: true,
      placeholder: 'Add comments...',
    }
  ];

  const actionButtons: ActionButton[] = [
    {
      label: 'Save',
      onClick: handleSave,
      variant: 'outlined',
      className: styles.saveButton,
      disabled: !hasSelectedRows || isSaving || isApproving,
      loading: isSaving,
    }
  ];

  if (isLoading) {
    return (
      <Box
        sx={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          minHeight: '400px',
        }}
      >
        <CircularProgress />
      </Box>
    );
  }

  return (
    <PolicyScannerTable
      title="List of Mapped Policies and Target Tables"
      subtitle="Review mapped policies and target table columns."
      complianceReviewName={complianceName}
      columns={columns}
      data={policies}
      showCheckbox={true}
      actionButtons={actionButtons}
      onCheckboxChange={handleCheckboxChange}
      onSelectAll={handleSelectAll}
      onCommentChange={handleCommentChange}
      isStepLoading={isSaving || isApproving}
      loadingMessage="Please wait, we are updating the policies."
    />
  );
};

export default MappedPoliciesTargetTablesPage;