import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Box, CircularProgress } from '@mui/material';
import PolicyScannerTable, { type ActionButton, type ColumnConfig } from '../PolicyScannerTable/PolicyScannerTable';
import EditTargetTableDialog from '../EditTargetTableDialog/EditTargetTableDialog';
import { SnowflakeMappingAPI } from '../../../../api/endpoints/policyScanner.api';
import type { PolicyItem } from '../../../../types/policyScanner.types';
import styles from '../../PolicyScanner.module.scss';
 
interface SnowflakeMappingPageProps {
  complianceId: string;
  complianceName: string;
  onLoadingChange?: (loading: boolean) => void;
 
  /** 🔹 New: auto trigger mapping after navigation into this step */
  autoGenerate?: boolean;
  /** 🔹 New: parent will reset the flag after first trigger */
  onAutoGenerateHandled?: () => void;
}
 
const SnowflakeMappingPage: React.FC<SnowflakeMappingPageProps> = ({
  complianceId,
  complianceName,
  onLoadingChange,
  autoGenerate = false,
  onAutoGenerateHandled,
}) => {
  const [policies, setPolicies] = useState<PolicyItem[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isSaving, setIsSaving] = useState<boolean>(false);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
 
  const [isEditDialogOpen, setIsEditDialogOpen] = useState<boolean>(false);
  const [editingPolicyId, setEditingPolicyId] = useState<number | string | null>(null);
 
  const selectedPolicies = useMemo(() => policies.filter((p) => p.selected), [policies]);
  const hasSelectedRows = selectedPolicies.length > 0;
 
  const editingPolicy = useMemo(
    () => policies.find((p) => String(p.id) === String(editingPolicyId)),
    [policies, editingPolicyId]
  );
 
  useEffect(() => {
    onLoadingChange?.(isLoading || isSaving || isGenerating);
  }, [isLoading, isSaving, isGenerating, onLoadingChange]);
 
  const refresh = useCallback(async () => {
    const response = await SnowflakeMappingAPI.getPolicies(complianceId);
    if (response?.success) setPolicies(response.policies ?? []);
    else setPolicies([]);
  }, [complianceId]);
 
  useEffect(() => {
    const fetchPolicies = async () => {
      if (!complianceId) return;
      setIsLoading(true);
      try {
        await refresh();
      } catch (error) {
        console.error('Error fetching policies:', error);
      } finally {
        setIsLoading(false);
      }
    };
 
    fetchPolicies();
  }, [complianceId, refresh]);
 
  const clearSelections = useCallback(() => {
    setPolicies((prev) => prev.map((p) => ({ ...p, selected: false })));
  }, []);
 
  const handleCheckboxChange = useCallback((id: number | string) => {
    setPolicies((prev) =>
      prev.map((policy) =>
        String(policy.id) === String(id) ? { ...policy, selected: !policy.selected } : policy
      )
    );
  }, []);
 
  const handleSelectAll = useCallback((selectAll: boolean) => {
    setPolicies((prev) => prev.map((policy) => ({ ...policy, selected: selectAll })));
  }, []);
 
  const handleEditMapping = useCallback((id: number | string) => {
    setEditingPolicyId(id);
    setIsEditDialogOpen(true);
  }, []);
 
  const handleCloseEditDialog = useCallback(() => {
    setIsEditDialogOpen(false);
    setEditingPolicyId(null);
  }, []);
 
  const handleEditConfirm = useCallback(
    (data: { database: string; schema: string; table: string }) => {
      if (editingPolicyId === null) return;
 
      const newTable = `${data.database}.${data.schema}.${data.table}`;
 
      setPolicies((prev) =>
        prev.map((policy) => {
          if (String(policy.id) !== String(editingPolicyId)) return policy;
 
          const existing = policy.autoGeneratedTable?.trim();
          const autoGeneratedTable = existing ? `${existing}, ${newTable}` : newTable;
 
          return {
            ...policy,
            autoGeneratedTable,
            database: data.database,
            schema: data.schema,
            targetTable: data.table,
          };
        })
      );
 
      handleCloseEditDialog();
    },
    [editingPolicyId, handleCloseEditDialog]
  );
 
  /**
   * ✅ Generate Mapping (agent call)
   */
  const handleGenerateMapping = useCallback(async () => {
    if (!complianceId) return;
    // Avoid double-trigger
    if (isGenerating) return;
 
    setIsGenerating(true);
    try {
      const prompt =
        `Generate Snowflake mapping for regulationId=${complianceId}. ` +
        `Use only approved policies. Create/insert mapping rows into mapping table DIM_POLICY_MAPPING.`;
 
      const agentResp = await SnowflakeMappingAPI.mappingAgent(prompt);
      console.log('mapping agent response:', agentResp);
 
      // If your agent returns the generated policies directly, use them immediately:
      if (agentResp?.success && Array.isArray(agentResp)) {
        setPolicies(agentResp);
      } else {
        // Otherwise, pull from backend persistence
        await refresh();
      }
 
      clearSelections();
    } catch (error) {
      console.error('Error generating mapping:', error);
    } finally {
      setIsGenerating(false);
    }
  }, [complianceId, refresh, clearSelections, isGenerating]);
 
  /**
   * 🔹 NEW: Auto-generate after entering this step (when requested by parent)
   */
  useEffect(() => {
    if (autoGenerate && !isGenerating) {
      // Fire & then let parent clear the flag
      handleGenerateMapping().finally(() => {
        onAutoGenerateHandled?.();
      });
    }
  }, [autoGenerate, isGenerating, handleGenerateMapping, onAutoGenerateHandled]);
 
  /**
   * ✅ Save only SELECTED rows
   */
  const handleSave = useCallback(async () => {
    if (!hasSelectedRows) return;
 
    setIsSaving(true);
    try {
      const policyDetails = selectedPolicies
        .map(
          (p) =>
            `policyId=${p.policyId},` +
            `policyDescription=${p.policyDescription},` +
            `targetTables=${p.autoGeneratedTable || ''},` +
            `targetTableColumns=${p.targetTableColumns || ''},` +
            `mappingIds=${p.mappingIds || ''}`
        )
        .join(' and ');
 
      const prompt = `For regulationId=${complianceId}, update the policy mapping with ${policyDetails}`;
      await SnowflakeMappingAPI.mappingAgent(prompt);
 
      await refresh();
      clearSelections();
    } catch (error) {
      console.error('Error saving mapping:', error);
    } finally {
      setIsSaving(false);
    }
  }, [complianceId, hasSelectedRows, selectedPolicies, refresh, clearSelections]);
 
  const columns: ColumnConfig[] = [
    { key: 'policyId', header: 'Policy ID', type: 'text', className: styles.policyIdColumn },
    { key: 'policyDescription', header: 'Policy description', type: 'text', className: styles.descriptionColumn },
    { key: 'autoGeneratedTable', header: 'Auto generated target table', type: 'text', className: styles.autoGeneratedColumn },
    { key: 'suggestedCount', header: 'Suggested count', type: 'text', className: styles.suggestedCountColumn },
    { key: 'action', header: 'Action', type: 'action', className: styles.actionColumn },
  ];
 
  const actionButtons: ActionButton[] = [
   
    {
      label: 'Save',
      onClick: handleSave,
      variant: 'outlined',
      className: styles.saveButton,
      disabled: !hasSelectedRows || isSaving || isGenerating,
      loading: isSaving,
    },
  ];
 
  if (isLoading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '400px' }}>
        <CircularProgress />
      </Box>
    );
  }
 
  return (
    <>
      <PolicyScannerTable
        title="Compliance Validation – Snowflake Mapping"
        subtitle="Review your Snowflake compliance mapping before proceeding."
        complianceReviewName={complianceName}
        columns={columns}
        data={policies}
        showCheckbox={true}
        actionButtons={actionButtons}
        onCheckboxChange={handleCheckboxChange}
        onSelectAll={handleSelectAll}
        onRowAction={(id) => handleEditMapping(id)}
        disableRowActions={isSaving || isGenerating}
        isStepLoading={isSaving || isGenerating}
        loadingMessage={
          isGenerating
            ? 'Generating Snowflake mapping...'
            : 'Please wait, we are updating the snowflake mapping changes.'
        }
      />
 
      <EditTargetTableDialog
        open={isEditDialogOpen}
        onClose={handleCloseEditDialog}
        onConfirm={handleEditConfirm}
        initialData={{
          database: editingPolicy?.database,
          schema: editingPolicy?.schema,
          table: editingPolicy?.targetTable,
        }}
      />
    </>
  );
};
 
export default SnowflakeMappingPage;