import type { DateRange } from './ui.types';

/**
 * Raw policy data from the API response
 */
export interface RawPolicyItem {
  POLICY_ID: number;
  POLICY_TEXT: string;
  POLICY_TYPE: string;
  CITATION_DOC: string;
  COMPLIANCE_DATA_REQUIREMENT: string;
  APPROVAL_STATUS: string;
  REGENERATION_COMMENT: string;

  // ✅ ADD THIS (backend sends it)
  CREATED_AT?: string;
}
export type ScheduledJobDbRow = {
  JOB_ID: number;
  REGULATION_ID: number;
  START_DATE: string;
  END_DATE: string;
  FREQUENCY: string;
  CRON_EXPR?: string;
  CREATED_AT?: string;
  UPDATED_AT?: string;
};

export type GetScheduledJobsResponse = {
  success: boolean;
  message?: string;
  data: ScheduledJobDbRow[];
  error?: string;
};

/**
 * Raw API response for getPolicies
 */
export interface RawGetPoliciesResponse {
  success: boolean;
  message: string;
  data: RawPolicyItem[];
}

/**
 * Policy Item structure used throughout the Policy Scanner workflow
 */
export interface PolicyItem {
  id: number | string;
  policyId: number | string;

  policyDescription: string;
  policyType?: string;

  citations: string;

  articleDisplay?: string;

  complianceDataRequirement?: string;

  comments: string;
  approvalStatus: string;

  selected: boolean;

  autoGeneratedTable?: string;
  suggestedCount?: number;
  database?: string;
  schema?: string;
  targetTable?: string;
  targetTableColumns?: string;
  commentsOnDeltaLoad?: string;
  complianceStatus?: 'Success' | 'Failed' | '';
  generatedSQL?: string;
  commentsOnSQL?: string;
  remediationSQL?: string;
  mappingIds?: string;
  approvedAt?: string;

  // ✅ already present (keep)
  createdAt?: string;
}

/**
 * Request to create a new compliance check
 */
export interface ComplianceCheckRequest {
  complianceName: string;
  pipelineId: string;
}

/**
 * Response from creating a compliance check
 */
export interface ComplianceCheckResponse {
  success: boolean;
  message: string;
  complianceId: string;
}

/**
 * Request to get policies for a compliance check
 */
export interface GetPoliciesRequest {
  complianceId: string;
}

/**
 * Response from getting policies
 */
export interface GetPoliciesResponse {
  success: boolean;
  message: string;
  policies: PolicyItem[];
}

/**
 * Request to regenerate policies
 */
export interface RegeneratePolicyRequest {
  policyIds: (string | number)[];
  complianceId: string;
}

/**
 * Response from regenerating policies
 */
export interface RegeneratePolicyResponse {
  success: boolean;
  message: string;
  policies: PolicyItem[];
}

/**
 * Request to save policies
 */
export interface SavePoliciesRequest {
  policies: PolicyItem[];
  complianceId: string;
}

/**
 * Response from saving policies
 */
export interface SavePoliciesResponse {
  success: boolean;
  message: string;
}

export interface GetRemediationResponse {
  limit: number;
  offset: number;
  policies: PolicyItem[];
}

/**
 * Request to approve policies
 */
export interface ApprovePoliciesRequest {
  policyIds: (string | number)[];
  complianceId: string;
}

/**
 * Response from approving policies
 */
export interface ApprovePoliciesResponse {
  success: boolean;
  message: string;
}

/**
 * Request to regenerate SQL for policies
 */
export interface RegenerateSQLRequest {
  policyIds: (string | number)[];
  complianceId: string;
  userComment: string;
}

/**
 * Response from regenerating SQL
 */
export interface RegenerateSQLResponse {
  success: boolean;
  message: string;
  policies: PolicyItem[];
}

/**
 * Request to schedule a compliance job
 */
export interface ScheduleJobRequest {
  complianceId: string;
  frequency: string;
  dateRange: DateRange;
}

/**
 * Response from scheduling a job
 */
export interface ScheduleJobResponse {
  success: boolean;
  message: string;
  data?: {
    jobId: number;
    regulationId: number;
    frequency: string;
    cron: string;
    startDate: string;
    endDate: string;
    at: string;
  } | null;
}

/**
 * Request to add a new policy
 */
export interface AddPolicyRequest {
  complianceId: string;
  policyDescription: string;
}

/**
 * Response from adding a new policy
 */
export interface AddPolicyResponse {
  success: boolean;
  message: string;
  policy: PolicyItem;
}

/**
 * Request to save target table mapping
 */
export interface SaveMappingRequest {
  complianceId: string;
  policyId: string | number;
  database: string;
  schema: string;
  table: string;
}

/**
 * Response from saving target table mapping
 */
export interface SaveMappingResponse {
  success: boolean;
  message: string;
}

/**
 * Request to generate compliance report
 */
export interface GenerateReportRequest {
  complianceId: string;
  policyId: string | number;
}

/**
 * Response from generating compliance report
 */
export interface GenerateReportResponse {
  success: boolean;
  message: string;
  reportUrl?: string;
}

/**
 * Response for database list
 */
export interface GetDatabasesResponse {
  success: boolean;
  message: string;
  databases: string[];
}

/**
 * Response for schema list
 */
export interface GetSchemasResponse {
  success: boolean;
  message: string;
  schemas: string[];
}

/**
 * Response for table list
 */
export interface GetTablesResponse {
  success: boolean;
  message: string;
  tables: string[];
}
