import React, { useCallback, useEffect, useMemo, useRef, useState, useId } from 'react';
import { Box, CircularProgress } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import styles from './ViewRACompliance.module.scss';
import { RAComplianceAPI } from '../../api/endpoints/racompliance.api';

import {
  ApprovedPoliciesAPI,
  MappedPoliciesAPI,
  ComplianceCheckAPI,
  RemediationScriptAPI,
  ScheduledJobsAPI,
} from '../../api/endpoints/policyScanner.api';

type PolicyItem = {
  id: any;
  policyId: any;

  policyDescription?: string;
  policyType?: string;
  citations?: string;
  articleDisplay?: string;

  complianceDataRequirement?: string;
  approvalStatus?: string;

  autoGeneratedTable?: string;
  targetTableColumns?: string;
  commentsOnDeltaLoad?: string;

  generatedSQL?: string;
  commentsOnSQL?: string;

  remediationSQL?: string;
  createdAt?: string;
};

type ApiGetPoliciesResponse = {
  success: boolean;
  message?: string;
  policies: PolicyItem[];
};

type TabKey = 'approved' | 'mapped' | 'check' | 'remediation' | 'schedule';

type ScheduledJobRow = {
  jobId: string;
  frequency: string;
  startDate: string;
  endDate: string;
};

type ScheduledJobsApiResponse = {
  success: boolean;
  message?: string;
  data: Array<{
    JOB_ID: number;
    REGULATION_ID: number;
    START_DATE: string;
    END_DATE: string;
    FREQUENCY: string;
    CRON_EXPR?: string;
    CREATED_AT?: string;
    UPDATED_AT?: string;
  }>;
};

const toDateOnly = (raw?: string) => {
  if (!raw) return '';
  const s = String(raw).trim();
  if (s.length >= 10 && /^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10);
  return s;
};

const isApproved = (p: PolicyItem) =>
  String(p.approvalStatus || '')
    .trim()
    .toUpperCase() === 'APPROVED';
const hasSQL = (v?: string) => Boolean(String(v || '').trim());

const safeId = (s: string) =>
  String(s || '')
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

const easeOutCubic = (t: number) => 1 - Math.pow(1 - t, 3);

const expandToSeries = (values: number[], points = 24) => {
  const clean = values.map((n) => (Number.isFinite(n) ? n : 0));
  if (clean.length === 0) return Array(points).fill(0);

  if (clean.length === 1) {
    const v = clean[0]!;
    return Array.from(
      { length: points },
      (_, i) => v * (0.6 + 0.4 * easeOutCubic(i / (points - 1)))
    );
  }

  if (clean.length === 2) {
    const [a, b] = clean as [number, number];
    return Array.from({ length: points }, (_, i) => {
      const t = i / (points - 1);
      return a + (b - a) * easeOutCubic(t);
    });
  }

  return clean;
};

const buildSmoothPath = (pts: { x: number; y: number }[]): string => {
  if (pts.length < 2) return '';

  const d: string[] = [];
  const first = pts[0]!;
  d.push(`M ${first.x} ${first.y}`);

  if (pts.length === 2) {
    const p1 = pts[0]!;
    const p2 = pts[1]!;
    const cp1x = p1.x + (p2.x - p1.x) / 3;
    const cp1y = p1.y + (p2.y - p1.y) / 3;
    const cp2x = p2.x - (p2.x - p1.x) / 3;
    const cp2y = p2.y - (p2.y - p1.y) / 3;
    d.push(`C ${cp1x} ${cp1y}, ${cp2x} ${cp2y}, ${p2.x} ${p2.y}`);
    return d.join(' ');
  }

  for (let i = 0; i < pts.length - 2; i++) {
    const p0 = pts[i - 1] ?? pts[i]!;
    const p1 = pts[i]!;
    const p2 = pts[i + 1]!;
    const p3 = pts[i + 2] ?? p2;

    const cp1x = p1.x + (p2.x - p0.x) / 6;
    const cp1y = p1.y + (p2.y - p0.y) / 6;
    const cp2x = p2.x - (p3.x - p1.x) / 6;
    const cp2y = p2.y - (p3.y - p1.y) / 6;

    d.push(`C ${cp1x} ${cp1y}, ${cp2x} ${cp2y}, ${p2.x} ${p2.y}`);
  }

  return d.join(' ');
};

const computePassRate = (policies: PolicyItem[]) => {
  const total = policies.length;
  if (!total) return 0;
  const approved = policies.filter(isApproved).length;
  return (approved / total) * 100;
};

const DonutCard: React.FC<{ title: string; passPercent: number }> = ({ title, passPercent }) => {
  const pass = Math.max(0, Math.min(100, Number(passPercent || 0)));
  const fail = 100 - pass;

  const r = 28;
  const dash = 2 * Math.PI * r;

  const passLen = (pass / 100) * dash;
  const failLen = (fail / 100) * dash;

  return (
    <div className={styles.metricCard}>
      <div className={styles.metricTitle}>{title}</div>

      <div className={styles.donutWrap}>
        <svg width="84" height="84" viewBox="0 0 84 84" aria-hidden="true">
          <circle cx="42" cy="42" r={r} stroke="#e5e7eb" strokeWidth="10" fill="none" />

          <circle
            cx="42"
            cy="42"
            r={r}
            stroke="#22c55e"
            strokeWidth="10"
            fill="none"
            strokeLinecap="round"
            strokeDasharray={`${passLen} ${dash - passLen}`}
            transform="rotate(-90 42 42)"
          />

          {failLen > 0 && (
            <circle
              cx="42"
              cy="42"
              r={r}
              stroke="#ef4444"
              strokeWidth="10"
              fill="none"
              strokeLinecap="round"
              strokeDasharray={`${failLen} ${dash - failLen}`}
              strokeDashoffset={-passLen}
              transform="rotate(-90 42 42)"
            />
          )}
        </svg>

        <div className={styles.donutText}>
          <div className={styles.donutValue}>{pass.toFixed(2)}%</div>
          <div className={styles.donutLabel}>Pass Rate</div>
        </div>
      </div>
    </div>
  );
};

const MiniAreaChart: React.FC<{
  title: string;
  subtitle?: string;
  data: number[];
  footerLeft?: string;
  footerRight?: string;
  unit?: string;
}> = ({ title, subtitle = 'KPI title', data, footerLeft, footerRight, unit = '' }) => {
  const reactId = useId();
  const gradId = useMemo(() => `grad-${safeId(title)}-${safeId(reactId)}`, [title, reactId]);
  const series = useMemo(() => expandToSeries(data, 26), [data]);

  const w = 320;
  const h = 120;
  const padTop = 8;
  const padBottom = 10;

  const max = Math.max(...series, 1);
  const min = Math.min(...series, 0);

  const sx = (i: number) => (i / (series.length - 1 || 1)) * w;
  const sy = (v: number) =>
    h - padBottom - ((v - min) / (max - min || 1)) * (h - padTop - padBottom);

  const pts = series.map((v, i) => ({ x: sx(i), y: sy(v) }));
  const lineD = buildSmoothPath(pts);
  const areaD = lineD ? `${lineD} L ${w} ${h} L 0 ${h} Z` : '';

  const lastIdx = series.length - 1;
  const last = series[lastIdx] ?? 0;
  const lastX = sx(lastIdx);
  const lastY = sy(last);

  return (
    <div className={styles.graphCard}>
      <div className={styles.graphTitle}>{title}</div>
      <div className={styles.graphSubTitle}>{subtitle}</div>

      <svg
        className={styles.graphSvg}
        viewBox="0 0 320 120"
        preserveAspectRatio="none"
        aria-hidden="true"
      >
        <g opacity="0.22" stroke="#cbd5e1" strokeWidth="1">
          {[20, 40, 60, 80, 100].map((y) => (
            <line key={y} x1="0" y1={y} x2="320" y2={y} />
          ))}
          {[40, 80, 120, 160, 200, 240, 280].map((x) => (
            <line key={x} x1={x} y1="0" x2={x} y2="120" />
          ))}
        </g>

        <defs>
          <linearGradient id={gradId} x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="#3b82f6" stopOpacity="0.35" />
            <stop offset="100%" stopColor="#3b82f6" stopOpacity="0.04" />
          </linearGradient>
        </defs>

        {areaD && <path d={areaD} fill={`url(#${gradId})`} />}
        {lineD && <path d={lineD} fill="none" stroke="#2563eb" strokeWidth="2.5" />}

        <g>
          <circle cx={lastX} cy={lastY} r="4" fill="#2563eb" />
          <rect
            x={Math.min(lastX + 10, 268)}
            y={Math.max(lastY - 14, 4)}
            rx="4"
            ry="4"
            width="50"
            height="18"
            fill="#e0f2fe"
            stroke="#bfdbfe"
          />
          <text
            x={Math.min(lastX + 35, 293)}
            y={Math.max(lastY + 1, 18)}
            fontSize="10"
            textAnchor="middle"
            fill="#0f172a"
          >
            {Math.round(last)}
            {unit}
          </text>
        </g>
      </svg>

      <div className={styles.axisLabels}>
        <span>X Axis</span>
        <span>Y Axis</span>
      </div>

      {(footerLeft || footerRight) && (
        <div className={styles.graphFooter}>
          <span>{footerLeft || ''}</span>
          <span>{footerRight || ''}</span>
        </div>
      )}
    </div>
  );
};

const ViewRACompliance: React.FC = () => {
  const params = useParams<{ id?: string; complianceId?: string; regulationId?: string }>();
  const complianceId = params.id || params.complianceId || params.regulationId || '';

  const navigate = useNavigate();
  const printableRef = useRef<HTMLDivElement>(null);

  const [activeTab, setActiveTab] = useState<TabKey>('approved');

  const [createdAtDate, setCreatedAtDate] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>('');

  const [approvedPolicies, setApprovedPolicies] = useState<PolicyItem[]>([]);
  const [mappedPolicies, setMappedPolicies] = useState<PolicyItem[]>([]);
  const [compliancePolicies, setCompliancePolicies] = useState<PolicyItem[]>([]);
  const [remediationPolicies, setRemediationPolicies] = useState<PolicyItem[]>([]);

  const [scheduledJobs, setScheduledJobs] = useState<ScheduledJobRow[]>([]);
  const [jobsLoading, setJobsLoading] = useState(false);
  const [jobsError, setJobsError] = useState<string>('');

  useEffect(() => {
    const fetchAll = async () => {
      if (!complianceId) {
        setError('Missing route param: id/complianceId/regulationId');
        return;
      }

      try {
        setLoading(true);
        setError('');
        setJobsLoading(true);
        setJobsError('');

        const [
          compliancesRes,
          approvedRes,
          mappedRes,
          complianceRes,
          remediationRes,
          scheduledRes,
        ] = await Promise.all([
          RAComplianceAPI.getCompliances() as Promise<any[]>,
          ApprovedPoliciesAPI.getPolicies(complianceId) as Promise<ApiGetPoliciesResponse>,
          MappedPoliciesAPI.getPolicies(complianceId) as Promise<ApiGetPoliciesResponse>,
          ComplianceCheckAPI.getPolicies(complianceId) as Promise<ApiGetPoliciesResponse>,
          RemediationScriptAPI.getPolicies(complianceId) as Promise<ApiGetPoliciesResponse>,
          ScheduledJobsAPI.getJobs(complianceId) as Promise<ScheduledJobsApiResponse | any>,
        ]);

        // ✅ Find and set regulation name
        const match = Array.isArray(compliancesRes)
          ? compliancesRes.find((r: any) => String(r.REGULATION_ID) === String(complianceId))
          : null;

        setRegulationName(match?.REGULATION_NAME || '');

        console.log('[ViewRACompliance] scheduledRes:', scheduledRes);

        if (!approvedRes.success)
          throw new Error(approvedRes.message || 'Failed to fetch approved policies');
        if (!mappedRes.success)
          throw new Error(mappedRes.message || 'Failed to fetch mapped policies');
        if (!complianceRes.success)
          throw new Error(complianceRes.message || 'Failed to fetch compliance check');
        if (!remediationRes.success)
          throw new Error(remediationRes.message || 'Failed to fetch remediation scripts');

        const approved = approvedRes.policies || [];
        setApprovedPolicies(approved);
        setMappedPolicies(mappedRes.policies || []);
        setCompliancePolicies(complianceRes.policies || []);
        setRemediationPolicies(remediationRes.policies || []);
        setCreatedAtDate(approved.length > 0 ? toDateOnly((approved[0] as any)?.createdAt) : '');

        const okJobs = scheduledRes?.success === true;
        const rows = Array.isArray(scheduledRes?.jobs)
          ? scheduledRes.jobs
          : Array.isArray(scheduledRes?.data)
            ? scheduledRes.data
            : Array.isArray(scheduledRes)
              ? scheduledRes
              : [];

        console.log('[ViewRACompliance] scheduled rows:', rows);

        if (!okJobs) {
          setJobsError(scheduledRes?.message || 'Failed to fetch scheduled jobs');
          setScheduledJobs([]);
        } else {
          const mappedJobs: ScheduledJobRow[] = rows.map((r: any) => ({
            jobId: String(r.jobId ?? r.JOB_ID ?? ''),
            frequency: String(r.frequency ?? r.FREQUENCY ?? ''),
            startDate: toDateOnly(String(r.startDate ?? r.START_DATE ?? '')),
            endDate: toDateOnly(String(r.endDate ?? r.END_DATE ?? '')),
          }));

          setScheduledJobs(mappedJobs);
        }
      } catch (e: any) {
        setError(e?.message || 'Fetch failed');
      } finally {
        setLoading(false);
        setJobsLoading(false);
      }
    };

    fetchAll();
  }, [complianceId]);
  const donutCards = useMemo(() => {
    const total = approvedPolicies.length;
    if (!total) return [];

    const counts = new Map<string, number>();
    for (const p of approvedPolicies) {
      const type = (p.policyType || 'Unknown').trim() || 'Unknown';
      counts.set(type, (counts.get(type) || 0) + 1);
    }

    return Array.from(counts.entries())
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([type, count]) => ({
        title: type,
        passPercent: (count / total) * 100,
      }));
  }, [approvedPolicies]);

  const metrics = useMemo(() => {
    const totalPolicies = approvedPolicies.length;

    const approvedCount = approvedPolicies.filter(isApproved).length;
    const pendingCount = Math.max(totalPolicies - approvedCount, 0);

    const mappedCount = mappedPolicies.length;
    const unmappedCount = Math.max(totalPolicies - mappedCount, 0);

    const complianceSQLCount = compliancePolicies.filter((p) => hasSQL(p.generatedSQL)).length;

    const remediationDistinct = new Set(
      remediationPolicies.filter((p) => hasSQL(p.remediationSQL)).map((p) => String(p.policyId))
    );
    const remediationSQLCount = remediationDistinct.size;

    return {
      totalPolicies,
      approvedCount,
      pendingCount,
      mappedCount,
      unmappedCount,
      complianceSQLCount,
      remediationSQLCount,
    };
  }, [approvedPolicies, mappedPolicies, compliancePolicies, remediationPolicies]);

  const overallPassRate = useMemo(() => {
    if (!approvedPolicies.length) return 0;
    return computePassRate(approvedPolicies);
  }, [approvedPolicies]);

  const graphApprovedRatio = useMemo(
    () => [metrics.pendingCount, metrics.approvedCount],
    [metrics.pendingCount, metrics.approvedCount]
  );
  const graphMappedCoverage = useMemo(
    () => [metrics.unmappedCount, metrics.mappedCount],
    [metrics.unmappedCount, metrics.mappedCount]
  );
  const graphComplianceSql = useMemo(
    () => [0, metrics.complianceSQLCount],
    [metrics.complianceSQLCount]
  );
  const graphRemediationSql = useMemo(
    () => [0, metrics.remediationSQLCount],
    [metrics.remediationSQLCount]
  );

  const exportActiveTabCSV = useCallback(() => {
    let header: string[] = [];
    let rows: any[][] = [];
    let fileName = `ra_compliance_${complianceId || 'review'}`;

    if (activeTab === 'approved') {
      header = [
        'Policy ID',
        'Policy Description',
        'Policy Type',
        'Data Requirement',
        'Citations',
        'Article Display',
        'Approval Status',
      ];
      rows = approvedPolicies.map((p) => [
        p.policyId,
        p.policyDescription || '',
        p.policyType || '',
        p.complianceDataRequirement || '',
        p.citations || '',
        p.articleDisplay || '',
        p.approvalStatus || '',
      ]);
      fileName += `_approved_policies.csv`;
    }

    if (activeTab === 'mapped') {
      header = [
        'Policy ID',
        'Policy description',
        'Auto generated target table',
        'Target table columns',
      ];
      rows = mappedPolicies.map((p) => [
        p.policyId,
        p.policyDescription || '',
        p.autoGeneratedTable || '',
        p.targetTableColumns || '',
      ]);
      fileName += `_mapped_policies.csv`;
    }

    if (activeTab === 'check') {
      header = ['Policy ID', 'Policy description', 'Generated SQL', 'Comments'];
      rows = compliancePolicies.map((p) => [
        p.policyId,
        p.policyDescription || '',
        p.generatedSQL || '',
        p.commentsOnSQL || '',
      ]);
      fileName += `_compliance_check.csv`;
    }

    if (activeTab === 'remediation') {
      header = ['Policy ID', 'Policy description', 'Remediation SQL', 'Comments'];
      rows = remediationPolicies.map((p) => [
        p.policyId,
        p.policyDescription || '',
        p.remediationSQL || '',
        p.commentsOnSQL || '',
      ]);
      fileName += `_remediation.csv`;
    }

    if (activeTab === 'schedule') {
      header = ['Job ID', 'Frequency', 'Start Date', 'End Date'];
      rows = scheduledJobs.map((j) => [j.jobId, j.frequency, j.startDate, j.endDate]);
      fileName += `_scheduled_jobs.csv`;
    }

    const csvContent = [header, ...rows]
      .map((r) =>
        r
          .map((cell) => {
            const v = String(cell ?? '');
            if (/[",\n]/.test(v)) return `"${v.replace(/"/g, '""')}"`;
            return v;
          })
          .join(',')
      )
      .join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  }, [
    activeTab,
    approvedPolicies,
    mappedPolicies,
    compliancePolicies,
    remediationPolicies,
    complianceId,
    scheduledJobs,
  ]);

  const handleExportPDF = () => window.print();
  const handleBack = () => navigate(-1);
  const [regulationName, setRegulationName] = useState<string>('');

  return (
    <div className={styles.container}>
      <Box className={styles.content} ref={printableRef}>
        <div className={styles.topBreadcrumb}>
          <div className={styles.appLabel}>Application</div>
          <div className={styles.pathLabel}>Regulatory &amp; Audit Compliance</div>
        </div>

        <header className={styles.headerRow}>
          <div className={styles.headerSpacer} />
          <div className={styles.headerCenter}>
            <h1 className={styles.pageTitle}>Regulatory &amp; Audit Compliance</h1>
            <div className={styles.subtitle}>{regulationName}</div>
          </div>

          <div className={styles.headerRight}>
            <input
              className={styles.dateRange}
              value={createdAtDate ? `Created At: ${createdAtDate}` : 'Created At'}
              readOnly
            />
          </div>
        </header>

        <section className={styles.reviewRow}>
          <div className={styles.sectionLabel}>
            {/* <strong>Compliance review:</strong>
            <span className={styles.sectionHighlight}>GDPR_Client_Claims_Check</span> */}
          </div>
        </section>

        {loading && <div className={styles.infoLine}>Loading…</div>}
        {error && <div className={styles.errorLine}>{error}</div>}

        <section className={styles.metricsGrid}>
          {donutCards.map((d) => (
            <DonutCard key={d.title} title={d.title} passPercent={d.passPercent} />
          ))}
          {!loading && donutCards.length === 0 && (
            <div className={styles.infoLine}>
              No approved policies found to build donut metrics.
            </div>
          )}
        </section>

        <section className={styles.graphGrid}>
          <MiniAreaChart
            title="Approved ratio"
            subtitle={`Overall pass rate: ${overallPassRate.toFixed(2)}%`}
            data={graphApprovedRatio}
            footerLeft={`Approved: ${metrics.approvedCount}`}
            footerRight={`Pending: ${metrics.pendingCount}`}
          />
          <MiniAreaChart
            title="Mapped coverage"
            subtitle="Mapped vs Unmapped"
            data={graphMappedCoverage}
            footerLeft={`Mapped: ${metrics.mappedCount}`}
            footerRight={`Unmapped: ${metrics.unmappedCount}`}
          />
          <MiniAreaChart
            title="Compliance SQL generated"
            subtitle="Rows having Generated SQL"
            data={graphComplianceSql}
            footerLeft={`Generated: ${metrics.complianceSQLCount}`}
            footerRight={`Total: ${metrics.totalPolicies}`}
          />
          <MiniAreaChart
            title="Remediation SQL generated"
            subtitle="Distinct policies having Remediation SQL"
            data={graphRemediationSql}
            footerLeft={`Generated: ${metrics.remediationSQLCount}`}
          />
        </section>

        <section className={styles.bottomSection}>
          <div className={styles.tabStrip} role="tablist">
            <button
              className={`${styles.tabBtn} ${activeTab === 'approved' ? styles.active : ''}`}
              onClick={() => setActiveTab('approved')}
            >
              List of defined policies
            </button>
            <button
              className={`${styles.tabBtn} ${activeTab === 'mapped' ? styles.active : ''}`}
              onClick={() => setActiveTab('mapped')}
            >
              Defined target table mapping
            </button>
            <button
              className={`${styles.tabBtn} ${activeTab === 'check' ? styles.active : ''}`}
              onClick={() => setActiveTab('check')}
            >
              Approved compliance SQL
            </button>
            <button
              className={`${styles.tabBtn} ${activeTab === 'remediation' ? styles.active : ''}`}
              onClick={() => setActiveTab('remediation')}
            >
              Remediation SQL
            </button>
            <button
              className={`${styles.tabBtn} ${activeTab === 'schedule' ? styles.active : ''}`}
              onClick={() => setActiveTab('schedule')}
            >
              Scheduled job
            </button>
          </div>

          {activeTab === 'approved' && (
            <div className={styles.tableWrapper}>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th>Policy ID</th>
                    <th>Policy Description</th>
                    <th>Policy Type</th>
                    <th>Data Requirement</th>
                    <th>Citations</th>
                    <th>Article Display</th>
                    <th>Approval Status</th>
                  </tr>
                </thead>
                <tbody>
                  {approvedPolicies.map((p, idx) => (
                    <tr key={`${p.id}-${idx}`}>
                      <td>{p.policyId}</td>
                      <td className={styles.wrapCell}>{p.policyDescription || ''}</td>
                      <td>{p.policyType || ''}</td>
                      <td className={styles.wrapCell}>{p.complianceDataRequirement || ''}</td>
                      <td>{p.citations || ''}</td>
                      <td>{p.articleDisplay || ''}</td>
                      <td className={styles.approvedPillCell}>
                        <span className={styles.approvedPill}>
                          {String(p.approvalStatus || '').toUpperCase()}
                        </span>
                      </td>
                    </tr>
                  ))}
                  {!loading && approvedPolicies.length === 0 && (
                    <tr>
                      <td colSpan={7} style={{ textAlign: 'center', padding: 12 }}>
                        No approved policies found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          )}

          {activeTab === 'mapped' && (
            <div className={styles.tableWrapper}>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th>Policy ID</th>
                    <th>Policy description</th>
                    <th>Auto generated target table</th>
                    <th>Target table columns</th>
                  </tr>
                </thead>
                <tbody>
                  {mappedPolicies.map((p, idx) => (
                    <tr key={`${p.id}-${idx}`}>
                      <td>{p.policyId}</td>
                      <td className={styles.wrapCell}>{p.policyDescription || ''}</td>
                      <td className={styles.wrapCell}>{p.autoGeneratedTable || ''}</td>
                      <td className={styles.wrapCell}>{p.targetTableColumns || ''}</td>
                    </tr>
                  ))}
                  {!loading && mappedPolicies.length === 0 && (
                    <tr>
                      <td colSpan={4} style={{ textAlign: 'center', padding: 12 }}>
                        No mapped policies found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          )}

          {activeTab === 'check' && (
            <div className={styles.tableWrapper}>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th>Policy ID</th>
                    <th>Policy description</th>
                    <th>Generated SQL</th>
                    <th>Comments</th>
                  </tr>
                </thead>
                <tbody>
                  {compliancePolicies.map((p, idx) => (
                    <tr key={`${p.id}-${idx}`}>
                      <td>{p.policyId}</td>
                      <td className={styles.wrapCell}>{p.policyDescription || ''}</td>
                      <td className={styles.sqlCell}>
                        <pre className={styles.sqlPre}>{p.generatedSQL || ''}</pre>
                      </td>
                      <td className={styles.wrapCell}>{p.commentsOnSQL || ''}</td>
                    </tr>
                  ))}
                  {!loading && compliancePolicies.length === 0 && (
                    <tr>
                      <td colSpan={4} style={{ textAlign: 'center', padding: 12 }}>
                        No compliance SQL found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          )}

          {activeTab === 'remediation' && (
            <div className={styles.tableWrapper}>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th>Policy ID</th>
                    <th>Policy description</th>
                    <th>Remediation SQL</th>
                    <th>Comments</th>
                  </tr>
                </thead>
                <tbody>
                  {remediationPolicies.map((p, idx) => (
                    <tr key={`${p.id}-${idx}`}>
                      <td>{p.policyId}</td>
                      <td className={styles.wrapCell}>{p.policyDescription || ''}</td>
                      <td className={styles.sqlCell}>
                        <pre className={styles.sqlPre}>{p.remediationSQL || ''}</pre>
                      </td>
                      <td className={styles.wrapCell}>{p.commentsOnSQL || ''}</td>
                    </tr>
                  ))}
                  {!loading && remediationPolicies.length === 0 && (
                    <tr>
                      <td colSpan={4} style={{ textAlign: 'center', padding: 12 }}>
                        No remediation SQL found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          )}

          {activeTab === 'schedule' && (
            <div className={styles.tableWrapper}>
              {jobsLoading && <div className={styles.infoLine}>Loading scheduled jobs…</div>}
              {jobsError && <div className={styles.errorLine}>{jobsError}</div>}

              <table className={styles.table} aria-label="Scheduled jobs">
                <thead>
                  <tr>
                    <th>Job ID</th>
                    <th>Frequency</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                  </tr>
                </thead>
                <tbody>
                  {scheduledJobs.map((j, idx) => (
                    <tr key={`${j.jobId}-${idx}`}>
                      <td>{j.jobId}</td>
                      <td>{j.frequency}</td>
                      <td>{j.startDate}</td>
                      <td>{j.endDate}</td>
                    </tr>
                  ))}
                  {!jobsLoading && scheduledJobs.length === 0 && (
                    <tr>
                      <td colSpan={4} style={{ textAlign: 'center', padding: 12 }}>
                        No scheduled jobs found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          )}
        </section>

        <div className={styles.footerActions}>
          <button onClick={handleBack} className={styles.backBtn}>
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              aria-hidden="true"
            >
              <path d="M19 12H5M12 19l-7-7 7-7" />
            </svg>
            Back
          </button>

          <button onClick={handleExportPDF} className={styles.exportBtn}>
            Export PDF
          </button>

          <button onClick={exportActiveTabCSV} className={styles.exportBtn}>
            Export CSV
          </button>
        </div>
      </Box>
      {loading && (
        <div className={styles.loaderOverlay} aria-hidden>
          <div className={styles.loaderInner}>
            <CircularProgress size={56} />
          </div>
        </div>
      )}
    </div>
  );
};

export default ViewRACompliance;
