export const ROUTES = {
  HOME: '/',
  APPLICATION: '/application',
  EXPERIMENT_DEPLOY: '/experiment-deploy',
  SERVICES: '/services',
  SERVICES_REGISTER: '/services/register',
  ACTIVITY_LOG: '/activity-log',
  SERVICE_MONITORING: '/service-monitoring',
  ERROR_MONITORING: '/error-monitoring',
  COST_CALCULATOR: '/cost-calculator',
  TEMPLATES: '/templates',
  EXPERIMENTATION: '/experimentation',
  EXPERIMENTATION_WITH_ID: '/experimentation/:chatbotId',
  TALK_TO_DATA: '/talk-to-data',
  DATA_PREPARATION: '/data-preparation',
  RA_COMPLIANCE: '/regulatory-audit-compliance',
  CREATE_RA_COMPLIANCE: '/create-ra-compliance',
  VIEW_RA_COMPLIANCE: '/view-ra-compliance',
  POLICY_SCANNER: '/policy-scanner',
  CREATE_PIPELINE: '/create-pipeline',
  EDIT_PIPELINE: '/edit-pipeline',
  PIPELINE_CONFIGURATION: '/pipeline-configuration',
  NOT_FOUND: '*',
  PROMPT_GENERATOR: '/prompt-generator',
  CREATE_CHATBOT: '/create-chatbot',
  SEARCH_CHATBOT: '/search-chatbot',
  DEPLOYED_APPLICATION: '/deployed-application',
  REVIEW_PIPELINE: '/review-pipeline',
  SEMANTIC_VIEW_AGENT: '/semantic-view-agent',
  SEMANTIC_VIEW_AGENT_VIEW: '/semantic-view-agent/view',
  SEMANTIC_VIEW_AGENT_EDIT: '/semantic-view-agent/edit',  
  LINEAGE_GRAPH: '/lineage-graph',
  LINEAGE_GRAPH_VIEW: '/lineage-graph/view',
  ACCESS_CONTROL: "/access-control",
  SETTINGS: "/settings",
  SNOWFLAKE_METRICS: "/account-insights",
  PII_SCANNER: "/pii-scanner",

};
   