-- ============================================================
-- LINEAGE TEST DATA: Large multi-layer pipeline with external sources
-- Run this entire script in Snowsight
-- Creates a 5-layer deep pipeline to test expansion functionality
-- ============================================================

USE ROLE X_IN_CAPG_POC_RWCX_AI_SCALABILITY_SOL;
USE WAREHOUSE W_IN_CAPG_AI_SCALABILITY_SOL_XS;
USE DATABASE D_IN_CAPG_POC_AI_SCALABILITY;
USE SCHEMA AI_SCALABILITY_SCHEMA;

-- ═══════════════════════════════════════════════════════════
-- LAYER 1: RAW TABLES (simulating data loaded from external sources)
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE TABLE R_RAW_CUSTOMERS (
  CUSTOMER_ID NUMBER,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(200),
  COUNTRY VARCHAR(50),
  SIGNUP_DATE DATE,
  LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
INSERT INTO R_RAW_CUSTOMERS VALUES
  (1, 'John', 'Smith', 'john@acme.com', 'USA', '2023-01-15', CURRENT_TIMESTAMP()),
  (2, 'Marie', 'Dupont', 'marie@globex.fr', 'France', '2023-03-22', CURRENT_TIMESTAMP()),
  (3, 'Raj', 'Patel', 'raj@tata.in', 'India', '2023-05-10', CURRENT_TIMESTAMP()),
  (4, 'Hans', 'Mueller', 'hans@sap.de', 'Germany', '2023-07-01', CURRENT_TIMESTAMP()),
  (5, 'Yuki', 'Tanaka', 'yuki@sony.jp', 'Japan', '2023-09-18', CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE R_RAW_ORDERS (
  ORDER_ID NUMBER,
  CUSTOMER_ID NUMBER,
  PRODUCT_ID NUMBER,
  ORDER_DATE DATE,
  QUANTITY NUMBER,
  UNIT_PRICE NUMBER(10,2),
  STATUS VARCHAR(20),
  LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
INSERT INTO R_RAW_ORDERS VALUES
  (1001, 1, 10, '2024-01-05', 3, 99.99, 'COMPLETED', CURRENT_TIMESTAMP()),
  (1002, 2, 20, '2024-01-12', 1, 249.99, 'COMPLETED', CURRENT_TIMESTAMP()),
  (1003, 3, 10, '2024-02-01', 5, 99.99, 'SHIPPED', CURRENT_TIMESTAMP()),
  (1004, 1, 30, '2024-02-15', 2, 499.99, 'COMPLETED', CURRENT_TIMESTAMP()),
  (1005, 4, 20, '2024-03-01', 1, 249.99, 'PENDING', CURRENT_TIMESTAMP()),
  (1006, 5, 40, '2024-03-10', 4, 79.99, 'COMPLETED', CURRENT_TIMESTAMP()),
  (1007, 2, 30, '2024-04-01', 1, 499.99, 'COMPLETED', CURRENT_TIMESTAMP()),
  (1008, 3, 10, '2024-04-15', 2, 99.99, 'RETURNED', CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE R_RAW_PRODUCTS (
  PRODUCT_ID NUMBER,
  PRODUCT_NAME VARCHAR(200),
  CATEGORY VARCHAR(100),
  BRAND VARCHAR(100),
  COST_PRICE NUMBER(10,2),
  LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
INSERT INTO R_RAW_PRODUCTS VALUES
  (10, 'Wireless Mouse', 'Electronics', 'LogiTech', 45.00, CURRENT_TIMESTAMP()),
  (20, 'Mechanical Keyboard', 'Electronics', 'Corsair', 120.00, CURRENT_TIMESTAMP()),
  (30, 'Ultra Monitor 27"', 'Electronics', 'Dell', 280.00, CURRENT_TIMESTAMP()),
  (40, 'USB-C Hub', 'Accessories', 'Anker', 35.00, CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE R_RAW_PAYMENTS (
  PAYMENT_ID NUMBER,
  ORDER_ID NUMBER,
  PAYMENT_METHOD VARCHAR(50),
  AMOUNT NUMBER(10,2),
  PAYMENT_DATE DATE,
  LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
INSERT INTO R_RAW_PAYMENTS VALUES
  (5001, 1001, 'CREDIT_CARD', 299.97, '2024-01-05', CURRENT_TIMESTAMP()),
  (5002, 1002, 'PAYPAL', 249.99, '2024-01-12', CURRENT_TIMESTAMP()),
  (5003, 1003, 'CREDIT_CARD', 499.95, '2024-02-01', CURRENT_TIMESTAMP()),
  (5004, 1004, 'BANK_TRANSFER', 999.98, '2024-02-15', CURRENT_TIMESTAMP()),
  (5005, 1005, 'CREDIT_CARD', 249.99, '2024-03-01', CURRENT_TIMESTAMP()),
  (5006, 1006, 'PAYPAL', 319.96, '2024-03-10', CURRENT_TIMESTAMP()),
  (5007, 1007, 'CREDIT_CARD', 499.99, '2024-04-01', CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE R_RAW_SHIPPING (
  SHIPMENT_ID NUMBER,
  ORDER_ID NUMBER,
  CARRIER VARCHAR(50),
  TRACKING_NUMBER VARCHAR(100),
  SHIPPED_DATE DATE,
  DELIVERED_DATE DATE,
  LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
INSERT INTO R_RAW_SHIPPING VALUES
  (8001, 1001, 'FedEx', 'FX123456', '2024-01-06', '2024-01-09', CURRENT_TIMESTAMP()),
  (8002, 1002, 'DHL', 'DH789012', '2024-01-13', '2024-01-17', CURRENT_TIMESTAMP()),
  (8003, 1003, 'UPS', 'UP345678', '2024-02-02', '2024-02-06', CURRENT_TIMESTAMP()),
  (8004, 1004, 'FedEx', 'FX901234', '2024-02-16', '2024-02-19', CURRENT_TIMESTAMP()),
  (8005, 1006, 'DHL', 'DH567890', '2024-03-11', '2024-03-15', CURRENT_TIMESTAMP());

-- ═══════════════════════════════════════════════════════════
-- LAYER 2: STAGING / CLEANED TABLES (CTAS from RAW)
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE TABLE R_STG_CUSTOMERS AS
SELECT
  CUSTOMER_ID,
  UPPER(FIRST_NAME || ' ' || LAST_NAME) AS FULL_NAME,
  LOWER(EMAIL) AS EMAIL,
  COUNTRY,
  SIGNUP_DATE
FROM R_RAW_CUSTOMERS;

CREATE OR REPLACE TABLE R_STG_ORDERS AS
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  PRODUCT_ID,
  ORDER_DATE,
  QUANTITY,
  UNIT_PRICE,
  QUANTITY * UNIT_PRICE AS LINE_TOTAL,
  STATUS
FROM R_RAW_ORDERS
WHERE STATUS != 'RETURNED';

CREATE OR REPLACE TABLE R_STG_PRODUCTS AS
SELECT
  PRODUCT_ID,
  PRODUCT_NAME,
  CATEGORY,
  BRAND,
  COST_PRICE
FROM R_RAW_PRODUCTS;

CREATE OR REPLACE TABLE R_STG_PAYMENTS AS
SELECT
  PAYMENT_ID,
  ORDER_ID,
  PAYMENT_METHOD,
  AMOUNT,
  PAYMENT_DATE
FROM R_RAW_PAYMENTS;

-- ═══════════════════════════════════════════════════════════
-- LAYER 3: DIMENSION & FACT TABLES (joins from staging)
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE TABLE R_DIM_CUSTOMER AS
SELECT
  c.CUSTOMER_ID,
  c.FULL_NAME,
  c.EMAIL,
  c.COUNTRY,
  c.SIGNUP_DATE,
  COUNT(o.ORDER_ID) AS TOTAL_ORDERS,
  SUM(o.LINE_TOTAL) AS LIFETIME_VALUE
FROM R_STG_CUSTOMERS c
LEFT JOIN R_STG_ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FULL_NAME, c.EMAIL, c.COUNTRY, c.SIGNUP_DATE;

CREATE OR REPLACE TABLE R_FACT_SALES AS
SELECT
  o.ORDER_ID,
  o.CUSTOMER_ID,
  o.PRODUCT_ID,
  p.PRODUCT_NAME,
  p.CATEGORY,
  p.BRAND,
  o.ORDER_DATE,
  o.QUANTITY,
  o.UNIT_PRICE,
  o.LINE_TOTAL,
  p.COST_PRICE,
  o.LINE_TOTAL - (o.QUANTITY * p.COST_PRICE) AS PROFIT,
  pay.PAYMENT_METHOD,
  pay.PAYMENT_DATE
FROM R_STG_ORDERS o
JOIN R_STG_PRODUCTS p ON o.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN R_STG_PAYMENTS pay ON o.ORDER_ID = pay.ORDER_ID;

CREATE OR REPLACE TABLE R_FACT_SHIPPING AS
SELECT
  s.SHIPMENT_ID,
  s.ORDER_ID,
  o.CUSTOMER_ID,
  s.CARRIER,
  s.TRACKING_NUMBER,
  s.SHIPPED_DATE,
  s.DELIVERED_DATE,
  DATEDIFF('day', s.SHIPPED_DATE, s.DELIVERED_DATE) AS DELIVERY_DAYS,
  o.LINE_TOTAL AS ORDER_VALUE
FROM R_RAW_SHIPPING s
JOIN R_STG_ORDERS o ON s.ORDER_ID = o.ORDER_ID;

-- ═══════════════════════════════════════════════════════════
-- LAYER 4: AGGREGATED / MART TABLES
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE TABLE R_MART_REVENUE_MONTHLY AS
SELECT
  DATE_TRUNC('MONTH', ORDER_DATE) AS MONTH,
  CATEGORY,
  BRAND,
  COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
  SUM(QUANTITY) AS UNITS_SOLD,
  SUM(LINE_TOTAL) AS TOTAL_REVENUE,
  SUM(PROFIT) AS TOTAL_PROFIT,
  AVG(LINE_TOTAL) AS AVG_ORDER_VALUE
FROM R_FACT_SALES
GROUP BY DATE_TRUNC('MONTH', ORDER_DATE), CATEGORY, BRAND;

CREATE OR REPLACE TABLE R_MART_CUSTOMER_SEGMENTS AS
SELECT
  CUSTOMER_ID,
  FULL_NAME,
  COUNTRY,
  TOTAL_ORDERS,
  LIFETIME_VALUE,
  CASE
    WHEN LIFETIME_VALUE > 1000 THEN 'PREMIUM'
    WHEN LIFETIME_VALUE > 500 THEN 'STANDARD'
    ELSE 'BASIC'
  END AS SEGMENT,
  CASE
    WHEN TOTAL_ORDERS >= 3 THEN 'LOYAL'
    WHEN TOTAL_ORDERS >= 2 THEN 'REPEAT'
    ELSE 'NEW'
  END AS LOYALTY_TIER
FROM R_DIM_CUSTOMER;

CREATE OR REPLACE TABLE R_MART_SHIPPING_PERFORMANCE AS
SELECT
  CARRIER,
  COUNT(*) AS TOTAL_SHIPMENTS,
  AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS,
  MIN(DELIVERY_DAYS) AS FASTEST_DELIVERY,
  MAX(DELIVERY_DAYS) AS SLOWEST_DELIVERY,
  SUM(ORDER_VALUE) AS TOTAL_SHIPPED_VALUE
FROM R_FACT_SHIPPING
GROUP BY CARRIER;

-- ═══════════════════════════════════════════════════════════
-- LAYER 5: REPORTING VIEWS (top of the pyramid)
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW VW_EXECUTIVE_DASHBOARD AS
SELECT
  r.MONTH,
  r.TOTAL_REVENUE,
  r.TOTAL_PROFIT,
  r.ORDER_COUNT,
  r.AVG_ORDER_VALUE,
  r.CATEGORY,
  s.TOTAL_SHIPMENTS,
  s.AVG_DELIVERY_DAYS
FROM R_MART_REVENUE_MONTHLY r
LEFT JOIN R_MART_SHIPPING_PERFORMANCE s ON 1=1
WHERE r.MONTH >= '2024-01-01';

CREATE OR REPLACE VIEW VW_CUSTOMER_360 AS
SELECT
  cs.CUSTOMER_ID,
  cs.FULL_NAME,
  cs.COUNTRY,
  cs.SEGMENT,
  cs.LOYALTY_TIER,
  cs.LIFETIME_VALUE,
  cs.TOTAL_ORDERS,
  fs.PRODUCT_NAME AS LAST_PRODUCT,
  fs.ORDER_DATE AS LAST_ORDER_DATE
FROM R_MART_CUSTOMER_SEGMENTS cs
LEFT JOIN R_FACT_SALES fs ON cs.CUSTOMER_ID = fs.CUSTOMER_ID;

CREATE OR REPLACE VIEW VW_PRODUCT_PERFORMANCE AS
SELECT
  CATEGORY,
  BRAND,
  SUM(UNITS_SOLD) AS TOTAL_UNITS,
  SUM(TOTAL_REVENUE) AS REVENUE,
  SUM(TOTAL_PROFIT) AS PROFIT,
  ROUND(SUM(TOTAL_PROFIT) / NULLIF(SUM(TOTAL_REVENUE), 0) * 100, 2) AS PROFIT_MARGIN_PCT
FROM R_MART_REVENUE_MONTHLY
GROUP BY CATEGORY, BRAND;

-- ═══════════════════════════════════════════════════════════
-- REGISTER EXTERNAL SOURCES (these appear in the graph)
-- ═══════════════════════════════════════════════════════════

DELETE FROM R_EXTERNAL_LINEAGE_SOURCES WHERE CREATED_BY = 'LINEAGE_TEST_SCRIPT';

INSERT INTO R_EXTERNAL_LINEAGE_SOURCES
  (SOURCE_NAMESPACE, SOURCE_NAME, SOURCE_TYPE, TARGET_DATABASE, TARGET_SCHEMA, TARGET_TABLE, DESCRIPTION, CREATED_BY)
VALUES
  -- S3 sources feeding RAW layer
  ('s3://capgemini-datalake-prod', 'crm/customers/full_export_2024.csv', 'S3',
   'D_IN_CAPG_POC_AI_SCALABILITY', 'AI_SCALABILITY_SCHEMA', 'R_RAW_CUSTOMERS',
   'Daily CRM customer export from Salesforce → S3 → Snowflake', 'LINEAGE_TEST_SCRIPT'),

  ('s3://capgemini-datalake-prod', 'ecommerce/orders/orders_stream.parquet', 'S3',
   'D_IN_CAPG_POC_AI_SCALABILITY', 'AI_SCALABILITY_SCHEMA', 'R_RAW_ORDERS',
   'Real-time order stream from e-commerce platform, Parquet format', 'LINEAGE_TEST_SCRIPT'),

  ('s3://capgemini-datalake-prod', 'catalog/products/product_master.json', 'S3',
   'D_IN_CAPG_POC_AI_SCALABILITY', 'AI_SCALABILITY_SCHEMA', 'R_RAW_PRODUCTS',
   'Product catalog master data from PIM system', 'LINEAGE_TEST_SCRIPT'),

  -- Postgres source
  ('postgres://payments-db.capg-prod.rds.amazonaws.com:5432', 'payment_service.transactions', 'POSTGRES',
   'D_IN_CAPG_POC_AI_SCALABILITY', 'AI_SCALABILITY_SCHEMA', 'R_RAW_PAYMENTS',
   'Payment transactions from Postgres payment microservice via CDC', 'LINEAGE_TEST_SCRIPT'),

  -- Kafka source
  ('kafka://kafka-cluster.capgemini-prod.com:9092', 'logistics.shipment.events', 'KAFKA',
   'D_IN_CAPG_POC_AI_SCALABILITY', 'AI_SCALABILITY_SCHEMA', 'R_RAW_SHIPPING',
   'Real-time shipment tracking events from logistics Kafka topic', 'LINEAGE_TEST_SCRIPT'),

  -- API source feeding additional data
  ('https://api.stripe.com/v1', 'charges/list?status=succeeded', 'API',
   'D_IN_CAPG_POC_AI_SCALABILITY', 'AI_SCALABILITY_SCHEMA', 'R_RAW_PAYMENTS',
   'Stripe payment confirmations via REST API webhook', 'LINEAGE_TEST_SCRIPT'),

  -- Azure Blob feeding products
  ('azure://capgstorage.blob.core.windows.net/product-images', 'metadata/product_attributes.csv', 'AZURE_BLOB',
   'D_IN_CAPG_POC_AI_SCALABILITY', 'AI_SCALABILITY_SCHEMA', 'R_RAW_PRODUCTS',
   'Product attribute metadata from Azure Blob (image processing pipeline)', 'LINEAGE_TEST_SCRIPT');

-- ═══════════════════════════════════════════════════════════
-- VERIFY: Check lineage exists (wait 1-2 minutes after running above)
-- ═══════════════════════════════════════════════════════════

-- Test downstream from a RAW table:
SELECT * FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE('D_IN_CAPG_POC_AI_SCALABILITY.AI_SCALABILITY_SCHEMA.R_RAW_CUSTOMERS', 'TABLE', 'DOWNSTREAM', 5));

-- Test upstream from a reporting view:
-- SELECT * FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE('D_IN_CAPG_POC_AI_SCALABILITY.AI_SCALABILITY_SCHEMA.VW_EXECUTIVE_DASHBOARD', 'TABLE', 'UPSTREAM', 5));
