USE ROLE X_IN_CAPG_POC_RWCX_AI_SCALABILITY_SOL;
USE WAREHOUSE W_IN_CAPG_AI_SCALABILITY_SOL_XS;
USE DATABASE D_IN_CAPG_POC_AI_SCALABILITY;
USE SCHEMA AI_SCALABILITY_SCHEMA;




-- Run ONCE as ACCOUNTADMIN or USERADMIN:
ALTER USER SF_COCO_USER_30013792 SET EMAIL = 'sajal.e.gupta@capgemini.com';