import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';

export type ModelResponse = {
  modelName: string;
  response: string;
};

export type DownloadResponsePdfPayload = {
  question: string;
  response: string;
  generatedAt?: string;
  userName?: string;
  resultsData?: Array<Record<string, any>>;
  sqlQuery?: string;
  planText?: string;
  chartElement?: HTMLElement | null;
  modelResponses?: ModelResponse[];
};

const sanitizeFileName = (value: string) =>
  String(value || '')
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 80);

const getTimestampForFileName = () => {
  const now = new Date();

  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  const ss = String(now.getSeconds()).padStart(2, '0');

  return `${yyyy}-${mm}-${dd}_${hh}-${min}-${ss}`;
};

export const downloadResponsePdf = async ({
  question,
  response,
  generatedAt,
  userName,
  resultsData,
  sqlQuery,
  planText,
  chartElement,
  modelResponses,
}: DownloadResponsePdfPayload) => {
  const doc = new jsPDF({
    orientation: 'p',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const maxWidth = pageWidth - margin * 2;

  let y = margin;

  // ── Watermark: draw on current page ──
  const drawWatermark = () => {
    const savedFont = doc.getFont();
    const savedSize = doc.getFontSize();
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const watermarkText = 'AI Scalability Platform  |  Snowflake  |  Capgemini';
    const textWidth = doc.getTextWidth(watermarkText);
    doc.text(watermarkText, pageWidth - margin - textWidth, 20);
    doc.setTextColor(0, 0, 0);
    doc.setFont(savedFont.fontName, savedFont.fontStyle);
    doc.setFontSize(savedSize);
  };

  // Draw watermark on first page
  drawWatermark();

  const ensureSpace = (heightNeeded: number) => {
    if (y + heightNeeded > pageHeight - margin) {
      doc.addPage();
      drawWatermark();
      y = margin;
    }
  };

  const addWrappedText = (
    text: string,
    options?: {
      fontSize?: number;
      bold?: boolean;
      lineHeight?: number;
      gapAfter?: number;
      font?: string;
    }
  ) => {
    const {
      fontSize = 11,
      bold = false,
      lineHeight = 18,
      gapAfter = 6,
      font = 'helvetica',
    } = options || {};

    doc.setFont(font, bold ? 'bold' : 'normal');
    doc.setFontSize(fontSize);

    const lines = doc.splitTextToSize(text || '', maxWidth);

    lines.forEach((line: string) => {
      ensureSpace(lineHeight);
      doc.text(line, margin, y);
      y += lineHeight;
    });

    y += gapAfter;
  };

  const addSectionHeader = (title: string) => {
    ensureSpace(30);
    // Draw a thin separator line
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 12;

    addWrappedText(title, {
      fontSize: 13,
      bold: true,
      lineHeight: 20,
      gapAfter: 6,
    });
  };

  // ── Title ──
  addWrappedText('Chatbot Response', {
    fontSize: 16,
    bold: true,
    lineHeight: 24,
    gapAfter: 12,
  });

  // ── Metadata Box (table style like Configuration & Metadata) ──
  const metaRows: string[][] = [];
  if (generatedAt) {
    metaRows.push(['Generated on', generatedAt]);
  }
  if (userName) {
    metaRows.push(['Generated by', userName]);
  }
  metaRows.push(['Prompt', question || 'N/A']);

  if (metaRows.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Property', 'Value']],
      body: metaRows,
      margin: { left: margin, right: margin },
      styles: { fontSize: 9, cellPadding: 6 },
      headStyles: {
        fillColor: [102, 187, 106],
        textColor: 255,
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { cellWidth: 100, fontStyle: 'bold' },
      },
      alternateRowStyles: { fillColor: [245, 247, 250] },
    });

    y = (doc as any).lastAutoTable.finalY + 16;
  }

  // ── Response ──
  if (modelResponses && modelResponses.length > 1) {
    // Multi-model: render each model with dark heading, no box around content
    modelResponses.forEach((modelResp, index) => {
      ensureSpace(60);

      // Model heading with dark background (black/charcoal)
      const headingHeight = 24;
      doc.setFillColor(50, 50, 50);
      doc.roundedRect(margin, y, maxWidth, headingHeight, 3, 3, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(255, 255, 255);
      doc.text(`Model ${index + 1}: ${modelResp.modelName}`, margin + 10, y + 16);
      doc.setTextColor(0, 0, 0);
      y += headingHeight + 10;

      // Response content: render line by line, only **text** portions in bold
      const responseText = modelResp.response || 'No response available.';
      const responseLines = responseText.split('\n');
      const lineH = 16;

      responseLines.forEach((line) => {
        const hasBold = /\*\*.+?\*\*/.test(line);
        const plainText = line.replace(/\*\*/g, '');

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);

        if (hasBold) {
          // Parse bold segments
          const segments: Array<{ text: string; bold: boolean }> = [];
          const boldRegex = /\*\*(.+?)\*\*/g;
          let lastIndex = 0;
          let match;
          while ((match = boldRegex.exec(line)) !== null) {
            if (match.index > lastIndex) {
              segments.push({ text: line.slice(lastIndex, match.index), bold: false });
            }
            segments.push({ text: match[1], bold: true });
            lastIndex = match.index + match[0].length;
          }
          if (lastIndex < line.length) {
            segments.push({ text: line.slice(lastIndex), bold: false });
          }

          // Use splitTextToSize on plain text to know how many lines it needs
          const wrappedLines: string[] = doc.splitTextToSize(plainText, maxWidth);

          // First line: render with mixed bold/normal (only if it fits)
          ensureSpace(lineH);
          let xPos = margin;
          let charsRendered = 0;
          const firstLineLen = wrappedLines[0]?.length || 0;

          for (const seg of segments) {
            if (charsRendered >= firstLineLen) break;
            const remainingChars = firstLineLen - charsRendered;
            const segText = seg.text.length <= remainingChars ? seg.text : seg.text.slice(0, remainingChars);

            doc.setFont('helvetica', seg.bold ? 'bold' : 'normal');
            doc.text(segText, xPos, y);
            xPos += doc.getTextWidth(segText);
            charsRendered += segText.length;
          }
          y += lineH;

          // Remaining wrapped lines rendered as normal
          doc.setFont('helvetica', 'normal');
          for (let i = 1; i < wrappedLines.length; i++) {
            ensureSpace(lineH);
            doc.text(wrappedLines[i], margin, y);
            y += lineH;
          }
        } else {
          // Normal line — no bold
          const wrappedLines = doc.splitTextToSize(plainText, maxWidth);
          wrappedLines.forEach((wLine: string) => {
            ensureSpace(lineH);
            doc.text(wLine, margin, y);
            y += lineH;
          });
        }
      });

      y += 16;
    });
  } else {
    // Single model or legacy: render single response
    ensureSpace(40);
    addSectionHeader('Response');
    addWrappedText(response || 'No response available.');
  }

  // ── Results Table ──
  if (resultsData && resultsData.length > 0) {
    addSectionHeader('Results');

    const columns = Object.keys(resultsData[0]!);
    const head = [columns];
    const body = resultsData.map((row) =>
      columns.map((col) =>
        row[col] !== null && row[col] !== undefined ? String(row[col]) : ''
      )
    );

    autoTable(doc, {
      startY: y,
      head,
      body,
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 4 },
      headStyles: {
        fillColor: [41, 128, 185],
        textColor: 255,
        fontStyle: 'bold',
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      didDrawPage: () => {
        drawWatermark();
      },
    });

    // Update y to where autoTable finished
    y = (doc as any).lastAutoTable.finalY + 16;
  }

  // ── SQL Query ──
  if (sqlQuery) {
    addSectionHeader('SQL Query');

    // Draw a light grey background box for the SQL
    doc.setFont('courier', 'normal');
    doc.setFontSize(9);

    const sqlLines = doc.splitTextToSize(sqlQuery, maxWidth - 16);
    const sqlLineHeight = 13;
    const sqlBlockHeight = sqlLines.length * sqlLineHeight + 16;

    ensureSpace(Math.min(sqlBlockHeight, 200));

    const boxY = y - 4;
    const boxHeight = Math.min(sqlBlockHeight, pageHeight - margin - y);
    doc.setFillColor(245, 245, 245);
    doc.roundedRect(margin, boxY, maxWidth, boxHeight, 3, 3, 'F');

    y += 8;
    sqlLines.forEach((line: string) => {
      ensureSpace(sqlLineHeight);
      doc.text(line, margin + 8, y);
      y += sqlLineHeight;
    });

    y += 12;
    doc.setFont('helvetica', 'normal');
  }

  // ── Data Visualization (Chart) ──
  if (chartElement) {
    addSectionHeader('Data Visualization');

    try {
      const canvas = await html2canvas(chartElement, {
        backgroundColor: '#ffffff',
        scale: 2,
        logging: false,
        useCORS: true,
      });

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = maxWidth;
      const imgHeight = (canvas.height / canvas.width) * imgWidth;

      ensureSpace(imgHeight + 10);
      doc.addImage(imgData, 'PNG', margin, y, imgWidth, imgHeight);
      y += imgHeight + 16;
    } catch {
      addWrappedText('(Chart could not be captured)', {
        fontSize: 10,
        gapAfter: 10,
      });
    }
  }

  // ── Plan ──
  if (planText && planText.trim().length > 0) {
    addSectionHeader('Plan');

    doc.setFont('courier', 'normal');
    doc.setFontSize(9);

    const planLines = doc.splitTextToSize(planText, maxWidth - 16);
    const planLineHeight = 13;

    const boxY = y - 4;
    const firstPageLines: string[] = [];
    let tempY = y + 8;

    // Calculate how many lines fit on current page
    for (const line of planLines) {
      if (tempY + planLineHeight > pageHeight - margin) break;
      firstPageLines.push(line);
      tempY += planLineHeight;
    }

    // Draw background for first page portion
    if (firstPageLines.length > 0) {
      const boxHeight = firstPageLines.length * planLineHeight + 16;
      doc.setFillColor(245, 245, 245);
      doc.roundedRect(margin, boxY, maxWidth, boxHeight, 3, 3, 'F');
    }

    y += 8;
    planLines.forEach((line: string) => {
      ensureSpace(planLineHeight);
      doc.text(line, margin + 8, y);
      y += planLineHeight;
    });

    y += 12;
    doc.setFont('helvetica', 'normal');
  }

  const baseName = sanitizeFileName(question || 'response') || 'response';
  const fileName = `${baseName}_${getTimestampForFileName()}.pdf`;

  doc.save(fileName);
};
