export type ModelResponse = {
  modelName: string;
  response: string;
};

export type DownloadResponseTxtPayload = {
  question: string;
  response: string;
  generatedAt?: string;
  userName?: string;
  resultsData?: Array<Record<string, any>>;
  sqlQuery?: string;
  planText?: string;
  modelResponses?: ModelResponse[];
};

const sanitizeFileName = (value: string) =>
  String(value || '')
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 80);

const getTimestampForFileName = () => {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  const ss = String(now.getSeconds()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}_${hh}-${min}-${ss}`;
};

export const downloadResponseTxt = ({
  question,
  response,
  generatedAt,
  userName,
  resultsData,
  sqlQuery,
  planText,
  modelResponses,
}: DownloadResponseTxtPayload) => {
  const sections: string[] = [];

  sections.push('CHATBOT RESPONSE');
  sections.push('='.repeat(50));

  if (generatedAt) {
    sections.push(`Generated on: ${generatedAt}`);
  }
  if (userName) {
    sections.push(`Generated by: ${userName}`);
  }

  sections.push('');
  sections.push('PROMPT:');
  sections.push('-'.repeat(30));
  sections.push(question || 'N/A');

  if (modelResponses && modelResponses.length > 1) {
    // Multi-model: render each model under its own heading
    modelResponses.forEach((modelResp, index) => {
      sections.push('');
      sections.push('='.repeat(50));
      sections.push(`MODEL ${index + 1}: ${modelResp.modelName}`);
      sections.push('='.repeat(50));
      sections.push(modelResp.response || 'No response available.');
    });
  } else {
    // Single model or legacy: render single response
    sections.push('');
    sections.push('RESPONSE:');
    sections.push('-'.repeat(30));
    sections.push(response || 'No response available.');
  }

  // Results Table
  if (resultsData && resultsData.length > 0) {
    sections.push('');
    sections.push('RESULTS:');
    sections.push('-'.repeat(30));

    const columns = Object.keys(resultsData[0]!);
    const header = columns.join('\t');
    sections.push(header);

    resultsData.forEach((row) => {
      const line = columns
        .map((col) => (row[col] !== null && row[col] !== undefined ? String(row[col]) : ''))
        .join('\t');
      sections.push(line);
    });
  }

  // SQL Query
  if (sqlQuery) {
    sections.push('');
    sections.push('SQL QUERY:');
    sections.push('-'.repeat(30));
    sections.push(sqlQuery);
  }

  // Plan
  if (planText && planText.trim().length > 0) {
    sections.push('');
    sections.push('PLAN:');
    sections.push('-'.repeat(30));
    sections.push(planText);
  }

  const content = sections.join('\n');
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const baseName = sanitizeFileName(question || 'response') || 'response';
  const fileName = `${baseName}_${getTimestampForFileName()}.txt`;

  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
