import {
  Document,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  HeadingLevel,
  BorderStyle,
  Packer,
  Header,
  AlignmentType,
  ShadingType,
} from 'docx';
import { saveAs } from 'file-saver';

export type ModelResponse = {
  modelName: string;
  response: string;
};

export type DownloadResponseDocxPayload = {
  question: string;
  response: string;
  generatedAt?: string;
  userName?: string;
  resultsData?: Array<Record<string, any>>;
  sqlQuery?: string;
  planText?: string;
  fileExtension?: 'docx' | 'doc';
  modelResponses?: ModelResponse[];
};

const sanitizeFileName = (value: string) =>
  String(value || '')
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 80);

const getTimestampForFileName = () => {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  const ss = String(now.getSeconds()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}_${hh}-${min}-${ss}`;
};

/** Parse a line for **bold** segments and return TextRun array */
const parseLineToRuns = (line: string, size = 20): TextRun[] => {
  const runs: TextRun[] = [];
  const boldRegex = /\*\*(.+?)\*\*/g;
  let lastIndex = 0;
  let match;

  while ((match = boldRegex.exec(line)) !== null) {
    if (match.index > lastIndex) {
      runs.push(new TextRun({ text: line.slice(lastIndex, match.index), size }));
    }
    runs.push(new TextRun({ text: match[1], bold: true, size }));
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < line.length) {
    runs.push(new TextRun({ text: line.slice(lastIndex), size }));
  }
  if (runs.length === 0) {
    runs.push(new TextRun({ text: line, size }));
  }
  return runs;
};

export const downloadResponseDocx = async ({
  question,
  response,
  generatedAt,
  userName,
  resultsData,
  sqlQuery,
  planText,
  fileExtension = 'docx',
  modelResponses,
}: DownloadResponseDocxPayload) => {
  const children: (Paragraph | Table)[] = [];

  // Title
  children.push(
    new Paragraph({
      text: 'Chatbot Response',
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    })
  );

  // ── Metadata Table (like PDF) ──
  const metaBorder = {
    style: BorderStyle.SINGLE,
    size: 1,
    color: 'CCCCCC',
  };
  const metaBorders = {
    top: metaBorder,
    bottom: metaBorder,
    left: metaBorder,
    right: metaBorder,
  };

  const metaRows: TableRow[] = [];

  // Header row
  metaRows.push(
    new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: 'Property', bold: true, size: 18, color: 'FFFFFF' })] })],
          borders: metaBorders,
          shading: { type: ShadingType.CLEAR, fill: '66BB6A', color: 'auto' },
          width: { size: 25, type: WidthType.PERCENTAGE },
        }),
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: 'Value', bold: true, size: 18, color: 'FFFFFF' })] })],
          borders: metaBorders,
          shading: { type: ShadingType.CLEAR, fill: '66BB6A', color: 'auto' },
          width: { size: 75, type: WidthType.PERCENTAGE },
        }),
      ],
    })
  );

  if (generatedAt) {
    metaRows.push(
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'Generated on', bold: true, size: 18 })] })],
            borders: metaBorders,
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: generatedAt, size: 18 })] })],
            borders: metaBorders,
          }),
        ],
      })
    );
  }

  if (userName) {
    metaRows.push(
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'Generated by', bold: true, size: 18 })] })],
            borders: metaBorders,
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: userName, size: 18 })] })],
            borders: metaBorders,
          }),
        ],
      })
    );
  }

  metaRows.push(
    new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: 'Prompt', bold: true, size: 18 })] })],
          borders: metaBorders,
        }),
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: question || 'N/A', size: 18 })] })],
          borders: metaBorders,
        }),
      ],
    })
  );

  children.push(new Paragraph({ text: '', spacing: { after: 100 } }));
  children.push(
    new Table({
      rows: metaRows,
      width: { size: 100, type: WidthType.PERCENTAGE },
    })
  );
  children.push(new Paragraph({ text: '', spacing: { after: 200 } }));

  // ── Response ──
  if (modelResponses && modelResponses.length > 1) {
    // Multi-model: render each model with a dark heading, no content box
    modelResponses.forEach((modelResp, index) => {
      // Model heading row (dark background, white text)
      const headingTable = new Table({
        rows: [
          new TableRow({
            children: [
              new TableCell({
                children: [
                  new Paragraph({
                    children: [new TextRun({ text: `Model ${index + 1}: ${modelResp.modelName}`, bold: true, size: 22, color: 'FFFFFF' })],
                  }),
                ],
                shading: { type: ShadingType.CLEAR, fill: '333333', color: 'auto' },
                borders: {
                  top: { style: BorderStyle.SINGLE, size: 1, color: '333333' },
                  bottom: { style: BorderStyle.SINGLE, size: 1, color: '333333' },
                  left: { style: BorderStyle.SINGLE, size: 1, color: '333333' },
                  right: { style: BorderStyle.SINGLE, size: 1, color: '333333' },
                },
              }),
            ],
          }),
        ],
        width: { size: 100, type: WidthType.PERCENTAGE },
      });

      children.push(new Paragraph({ text: '', spacing: { after: 100 } }));
      children.push(headingTable);
      children.push(new Paragraph({ text: '', spacing: { after: 100 } }));

      // Response content as plain paragraphs (bold only for **headings**)
      const modelLines = (modelResp.response || 'No response available.').split('\n');
      modelLines.forEach((line) => {
        children.push(
          new Paragraph({
            children: parseLineToRuns(line, 20),
            spacing: { after: 80 },
          })
        );
      });

      children.push(new Paragraph({ text: '', spacing: { after: 200 } }));
    });
  } else {
    // Single model or legacy: render single response
    children.push(
      new Paragraph({
        text: 'Response:',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 100 },
      })
    );

    const responseLines = (response || 'No response available.').split('\n');
    responseLines.forEach((line) => {
      children.push(
        new Paragraph({
          children: parseLineToRuns(line, 20),
          spacing: { after: 80 },
        })
      );
    });
  }

  // Results Table
  if (resultsData && resultsData.length > 0) {
    children.push(
      new Paragraph({
        text: 'Results',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      })
    );

    const columns = Object.keys(resultsData[0]!);
    const borderStyle = {
      style: BorderStyle.SINGLE,
      size: 1,
      color: '999999',
    };
    const borders = {
      top: borderStyle,
      bottom: borderStyle,
      left: borderStyle,
      right: borderStyle,
    };

    // Header row
    const headerRow = new TableRow({
      children: columns.map(
        (col) =>
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: col, bold: true, size: 18 })] })],
            borders,
          })
      ),
    });

    // Data rows
    const dataRows = resultsData.map(
      (row) =>
        new TableRow({
          children: columns.map(
            (col) =>
              new TableCell({
                children: [
                  new Paragraph({
                    text: row[col] !== null && row[col] !== undefined ? String(row[col]) : '',
                    style: undefined,
                  }),
                ],
                borders,
              })
          ),
        })
    );

    const table = new Table({
      rows: [headerRow, ...dataRows],
      width: { size: 100, type: WidthType.PERCENTAGE },
    });

    children.push(new Paragraph({ text: '' })); // spacer
    children.push(table);
  }

  // SQL Query
  if (sqlQuery) {
    children.push(
      new Paragraph({
        text: 'SQL Query',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      })
    );
    const sqlLines = sqlQuery.split('\n');
    sqlLines.forEach((line) => {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, font: 'Courier New', size: 18 })],
          spacing: { after: 40 },
        })
      );
    });
  }

  // Plan
  if (planText && planText.trim().length > 0) {
    children.push(
      new Paragraph({
        text: 'Plan',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      })
    );
    const planLines = planText.split('\n');
    planLines.forEach((line) => {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, font: 'Courier New', size: 18 })],
          spacing: { after: 40 },
        })
      );
    });
  }

  // Watermark header (top-right on every page)
  const watermarkHeader = new Header({
    children: [
      new Paragraph({
        alignment: AlignmentType.RIGHT,
        children: [
          new TextRun({
            text: 'AI Scalability Platform  |  Snowflake  |  Capgemini',
            size: 16,
            color: '999999',
          }),
        ],
      }),
    ],
  });

  const doc = new Document({
    sections: [{
      headers: {
        default: watermarkHeader,
      },
      children: children as any[],
    }],
  });

  const blob = await Packer.toBlob(doc);
  const baseName = sanitizeFileName(question || 'response') || 'response';
  const fileName = `${baseName}_${getTimestampForFileName()}.${fileExtension}`;
  saveAs(blob, fileName);
};
